frontend:
   build: frontend
   entrypoint: /var/local/application/target/universal/stage/bin/frontend
   command: -Dconfig.file=/etc/opt/frontend/docker.conf
   links:
      - "service"
   ports:
      - "49910:9000"
   volumes:
#      - ./frontend:/var/local/application:rw
      - frontend/conf:/etc/opt/frontend:ro
   volumes_from:
      - maven
service:
   build: service
   command: run -Dconfig.file=/etc/opt/service/docker.conf
   links:
      - "database"
   ports:
      - "49920:8880"
   expose:
      - "8880"
   volumes:
#      - service:/var/local/application:rw
      - service/src/main/resources:/etc/opt/service:ro
   volumes_from:
      - maven
database:
   image: postgres:9.4
#   ports:
#      - "49932:5432"
   expose:
      - "5432"
maven:
   image: debian:wheezy
   volumes:
      - ~/.m2:/root/.m2:rw
      - ~/.ivy2:/root/.ivy2:rw
      - frontend/repositories:/root/.sbt/repositories:ro

